[project]
name = "PyHund-r8"
version = "8.0.0"
description = "Adaptive and modular OSINT web-scraping tool used to detect user-instances across the internet"
readme = "ReadMe.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32.5",
]
